### ISSUE TITLE
Dedupe definitions

### ISSUE THREAD

**Issue by michal-wknd** [DanielAndrews43/slack-acronym-bot#11]
There doesn't seem to be a way to de-dupe definitions right now, so we could have any number of the exact same definition for the same term. Could you add a command to dedupe, and maybe also edit the "add new" command so that if the same definition already exists, it won't be added again? Maybe this could also apply to capitalization + formatting (e.g. italics) - so that definitions are not case-sensitive? Thanks!

**Comment by DanielAndrews43** [comment]
Happy to review / merge a pull request if you make one

**Comment by michal-wknd** [comment]
thank you, please see https://github.com/DanielAndrews43/slack-acronym-bot/pull/12

**Comment by michal-wknd** [comment]
hi @DanielAndrews43 , wondering if you've had a chance to look at my PR? thanks!

**Comment by DanielAndrews43** [comment]
Merged, thanks for the contribution
