### ISSUE TITLE
Make acronym bot less narky to avoid shaming people

### ISSUE THREAD

**Issue by caseyfw** [DanielAndrews43/slack-acronym-bot#5]
Hi Dan, and thanks for making Acronym Bot!

Just a feature request - could you make possible to remove the requesting user name from the `<user> needs to define <acronym>!` message that gets posted to a channel?

It would be great if users could anonymously request definitions of things to avoid scenarios like this:

![image](https://user-images.githubusercontent.com/248665/119758426-df6c3480-bee9-11eb-8730-7df0d849cd3f.png)

Thanks!

**Comment by DanielAndrews43** [comment]
Feel free to make a PR to silence the name using a keyword like `/explain silent <word>`.

Going to leave as is for now as we use it to follow up with people who may need more help with an acronym or definition
