### ISSUE TITLE
Feat: Retrieve All already defined acronyms

### ISSUE THREAD

**Issue by mtahat** [DanielAndrews43/slack-acronym-bot#6]
**Scenario:** 
> **As a Slack acronym-bot user**
> I would like to have the ability to **retrieve all already defined acronyms in my channel.**
> So that I can create **Dictionary that can be used as a reference point for all acronyms in my org.**

**Suggested Format:** 
`/explain *`
`/explain <all>`
`/explain -c dictionary`

<img width="745" alt="image" src="https://user-images.githubusercontent.com/45109004/131049317-0452dddc-72a1-4b35-826d-83246b2601ba.png">

**Comment by CarolynWebster** [comment]
Agreed - this would be really helpful for new hires so they can see all the acronyms without having to know what to search for!

**Comment by DanielAndrews43** [comment]
Whoop, I'll add this to the readme, thanks for pointing it out
